export interface PolicyItem {
  title: string;
  text: string;
  points?: string[];
}

export interface PolicySection {
  id: string;
  title: string;
  badge: string;
  description: string;
  lastUpdated: string;
  items: PolicyItem[];
}

export const RGAMER_POLICIES: PolicySection[] = [
  {
    id: 'privacy',
    title: 'Privacy Policy',
    badge: 'Data & Security',
    lastUpdated: 'September 2026',
    description: 'How RGAMER AI protects your account, private messages, code snippets, and session data.',
    items: [
      {
        title: '1. Information We Collect',
        text: 'When you sign in and interact with RGAMER AI, we collect only the minimal data required to provide a personalized, persistent workspace:',
        points: [
          'Account Details: Your Google Email address, Display Name, and unique Google Authentication User ID (UID).',
          'Chat Conversations: The prompts, Python scripts, Blender queries, and AI responses created within your chat sessions.',
          'Local Preferences: Your chosen nickname, UI theme (Dark/Light/System), and Custom System Instructions stored locally in your browser storage.'
        ]
      },
      {
        title: '2. Complete Data Isolation & Encryption',
        text: 'Your privacy is guaranteed through strict database partitioning and modern security practices:',
        points: [
          'Strict User-Level Pathing: All your chats and messages are stored under `users/{userId}/sessions` in Google Cloud Firestore.',
          'No Cross-Account Access: No other user, account holder, or third-party can read, search, or alter your chat sessions.',
          'Transport Security: All communication between your browser, our servers, and AI inference engines is encrypted using TLS 1.3 / HTTPS.'
        ]
      },
      {
        title: '3. Zero Data Selling & Intellectual Protection',
        text: 'We respect your intellectual property and confidential workflow:',
        points: [
          'We NEVER sell, rent, or trade your personal data, code, or prompts to data brokers, advertisers, or external marketing entities.',
          'Your prompts are sent directly to high-performance inference servers solely to generate your immediate code or answers.',
          'We do not train public AI models on your proprietary 3D scripts or private projects.'
        ]
      },
      {
        title: '4. Your Data Rights & Complete Control',
        text: 'You maintain full ownership and total control over your digital footprint:',
        points: [
          'Instant Chat Deletion: You can delete any individual chat session at any time with one click. This permanently removes all messages from the database.',
          'One-Click Wipe: You can clear all session history through the Account Settings tab.',
          'Account Unlink: Logging out terminates your active authentication token immediately.'
        ]
      }
    ]
  },
  {
    id: 'commercial',
    title: 'Commercial & Watermark Policy',
    badge: 'Attribution Rules',
    lastUpdated: 'September 2026',
    description: 'Mandatory guidelines for using RGAMER AI generated images, videos, 3D renders, and media in commercial projects.',
    items: [
      {
        title: '1. Commercial Usage Rights & Permissions',
        text: 'Users are permitted to use images, animations, video renders, 3D assets, and code generated by RGAMER AI for commercial purposes (including commercial video games, YouTube videos, film productions, marketing campaigns, client commissions, and digital products) subject to the strict attribution terms below.'
      },
      {
        title: '2. Watermark Preservation Requirement (Crucial)',
        text: 'If an image, video, render, or graphic generated by RGAMER AI includes a watermark, stamp, or digital badge:',
        points: [
          'You MUST NOT remove, crop, blur, mask, or obscure the RGAMER AI watermark or stamp from the visual asset.',
          'The watermark must remain legible and intact when displayed in public media or commercial distribution.'
        ]
      },
      {
        title: '3. Mandatory Attribution if Watermark is Removed or Absent',
        text: 'If you remove the watermark, edit the asset, integrate it into a composition where the original watermark is cropped or omitted, or if the media format did not render a default watermark, you MUST provide visible credit to RGAMER AI:',
        points: [
          'Visible On-Screen Credit: In your video, game, commercial product, or promotional media, you MUST clearly display the text: "Made by RGAMER AI" (or "Powered by RGAMER AI" / "Created with RGAMER AI") visibly on the side of the screen, during the credits, or in the media description.',
          'Official Logo Display: Alternatively, you may prominently display the official RGAMER AI logo on your product screen, title card, end screen, or packaging.',
          'Commercial Games & Apps: If used in an indie game or mobile application, include "RGAMER AI" in the game credits or attribution screen.'
        ]
      },
      {
        title: '4. Consequences of Non-Compliance',
        text: 'Using RGAMER AI assets in commercial ventures while intentionally removing the watermark without displaying the required "Made by RGAMER AI" attribution constitutes a violation of these Terms of Service and may result in revocation of commercial rights and account suspension.'
      },
      {
        title: '5. Non-Commercial & Educational Use',
        text: 'For non-commercial personal projects, private testing, school assignments, or educational study, attribution is warmly appreciated but not legally required.'
      }
    ]
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    badge: 'Usage Rules',
    lastUpdated: 'September 2026',
    description: 'The terms and guidelines governing your usage of RGAMER AI, code generation, and scripting tools.',
    items: [
      {
        title: '1. License & Usage Grant',
        text: 'RGAMER AI grants you a personal, non-exclusive, revocable right to access and use this platform for software engineering, 3D modeling, Blender scripting automation, learning, and creative tasks.'
      },
      {
        title: '2. Output Ownership & Commercial Rights',
        text: 'You retain full ownership of the intellectual property in the code, Blender Python (bpy) automation scripts, visual concepts, and creative works generated with RGAMER AI, subject to the Commercial & Watermark Policy specified herein.'
      },
      {
        title: '3. Blender & Python Execution Responsibility',
        text: 'RGAMER AI strives for high precision in Blender bpy scripting, GLSL shaders, and Python utilities. However, AI-generated code can occasionally contain syntax deprecations or runtime errors.',
        points: [
          'Always test scripts in a clean Blender file or backed-up scene before running in production pipelines.',
          'Users are solely responsible for verifying that scripts do not overwrite important scene files or assets.',
          'RGAMER AI is not liable for scene loss or corrupted blend files resulting from running untested code.'
        ]
      },
      {
        title: '4. Acceptable Use Policy',
        text: 'You agree not to use RGAMER AI to:',
        points: [
          'Generate malicious software, viruses, rootkits, DDoS scripts, or keyloggers.',
          'Attempt unauthorized penetration testing, vulnerability exploitation, or hacking.',
          'Circumvent rate limits, spam our inference backend, or perform automated data scraping.',
          'Impersonate other individuals, harass creators, or distribute harmful misinformation.'
        ]
      },
      {
        title: '5. Subscriptions & Tier Limits',
        text: 'The Free Tier allows up to 5 simultaneous saved chat sessions with full Blender 3D and coding features. Upgrading to PRO or GAMER Tier unlocks unlimited persistent storage, priority GPU processing, and advanced visual capabilities.'
      }
    ]
  },
  {
    id: 'safety',
    title: 'Content & Safety Guidelines',
    badge: 'Family-Friendly',
    lastUpdated: 'September 2026',
    description: 'Our strict safety principles ensuring a secure, welcoming, and productive environment for creators of all ages.',
    items: [
      {
        title: '1. Family-Friendly & Safe AI Guardrails',
        text: 'RGAMER AI is designed to be accessible, educational, and safe for creators of all ages, including young game developers and students:',
        points: [
          'Zero Tolerance for Adult Content: Explicit adult content (18+ / NSFW), nudity, or sexually suggestive material is strictly prohibited and automatically blocked.',
          'Zero Tolerance for Harmful Acts: Suicide, self-harm promotion, cyberbullying, hate speech, and harassment are strictly prohibited.',
          'Child Protection: Full compliance with digital safety standards protecting minors from inappropriate material.'
        ]
      },
      {
        title: '2. Code Safety & System Protection',
        text: 'Our AI system prompts actively filter out dangerous shell commands (such as recursive directory deletion, root privilege escalation, or destructive drive formatting) to protect your workstation and operating system.'
      },
      {
        title: '3. Continuous Monitoring & Filter Upgrades',
        text: 'We regularly upgrade our safety heuristics and prompt sanitizers to maintain a creative, focused, and respectful community environment.'
      }
    ]
  },
  {
    id: 'credits',
    title: 'Creator & Credits',
    badge: 'About the Project',
    lastUpdated: 'September 2026',
    description: 'Attributions, software acknowledgments, and development information.',
    items: [
      {
        title: 'Creator & Lead Developer',
        text: 'RGAMER AI was conceptualized, built, and designed by Reyansh Verma (RGAMER). Dedicated to empowering 3D artists, indie game creators, and programmers with fast, intelligent assistants.'
      },
      {
        title: 'Core Technologies & Infrastructure',
        text: 'RGAMER AI is powered by high-performance technologies:',
        points: [
          'Front-End: React 18, TypeScript, Tailwind CSS, Lucide Icons, and Motion.',
          'Database & Authentication: Google Firebase Firestore & Google Identity Services.',
          'AI Acceleration: High-speed LLM inference engines with Groq Hardware Acceleration.',
          '3D Integration: Designed specifically for the Blender Foundation ecosystem (bpy Python API).'
        ]
      },
      {
        title: 'Trademarks & Disclaimers',
        text: 'Blender is a registered trademark of the Blender Foundation. Python is a registered trademark of the Python Software Foundation. RGAMER AI is an independent development suite and is not officially affiliated with or endorsed by the Blender Foundation.'
      }
    ]
  }
];

